# Testing of objects in Assignment 3 Part 1
# whenever a pull request or commit (merge) is made
# to one of the data set branches
# Assisted by Gemini (Google AI)

name: ottr Tests
on:
  push:
    branches:
      - 'R/*'
  pull_request:
    branches:
      - 'R/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Load root directory into working directory
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1' # Latest version

      - name: Install Dependencies
        run: |
          Rscript -e "install.packages(c('ottr', 'tinytest', 'testthat', 'dplyr', 'readr'), repos = 'https://cran.rstudio.com/')"

      - name: Run ottr Tests and Publish Report
        run: |
          Rscript -e "library(ottr); library(tinytest); library(testthat); test_dir('[WLU-F24-DATA100] Assignment 03-Part 01.Rmd'); ottr::publish_report(file = 'ottr_report.html')"
        if: ${{ always() }} # Always run this step, even if previous steps fail

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ottr-report
          path: ottr_report.html
        if: ${{ steps.test.outputs.test-result == 'success' }} # Only upload if tests pass

    outputs:
      test-result: ${{ steps.test.conclusion }}
