# Testing of objects in Assignment 3 Part 1
# whenever a pull request or commit (merge) is made
# to one of the data set branches
# Assisted by Gemini (Google AI)

name: ottr Tests
on:
  push:
    branches:
      - 'R/Pt-1-*'
    paths:
      - 'Assignment 03-Part 01.Rmd'
  pull_request:
    branches:
      - 'R/Pt-1-*'
    paths:
      - 'Assignment 03-Part 01.Rmd'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.R/library
          key: ${{ runner.os }}-r-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1' # Latest version

      - name: Install Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::ottr
            any::tinytest
            any::testthat
            any::dplyr
            any::readr
          needs: check

      - name: Get current directory
        run: pwd

      - name: Run Tests and Get Report
        run: Rscript -e "test_dir('./tests'); ottr::publish_report(file = 'ottr_report.html')"

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ottr-report
          path: ottr_report.html
        if: ${{ steps.test.outputs.test-result == 'success' }} # Only upload if tests pass

    outputs:
      test-result: ${{ steps.test.conclusion }}
